# Generated by Django 5.1.2 on 2024-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre_image',
            field=models.ImageField(default='mri_images/predicted_img/', upload_to='mri_images/predicted_img/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
