# Generated by Django 5.1.2 on 2024-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor', '0002_patient_email_patient_pre_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pre_image',
            field=models.ImageField(blank=True, null=True, upload_to='mri_images/predicted_img/'),
        ),
    ]
