# Generated by Django 5.1.2 on 2024-10-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor', '0003_alter_patient_pre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
