# Generated by Django 5.1.2 on 2024-11-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_tumor', '0006_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mri_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pre_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prediction_date',
        ),
        migrations.CreateModel(
            name='MRIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri_image', models.ImageField(upload_to='mri_images/')),
                ('pre_image', models.ImageField(blank=True, null=True, upload_to='mri_images/predicted_img/')),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_images', to='brain_tumor.patient')),
            ],
        ),
    ]
